title: "Maia Czerwonka"
description: "Personal Page"
sidebar_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/maiacz
  - title: GitHub
    url: https://github.com/maiacz
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
